export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE'

export const POST_LIKE_REQUEST = 'POST_LIKE_REQUEST'
export const POST_LIKE_SUCCESS = 'POST_LIKE_SUCCESS'
export const POST_LIKE_FAILURE = 'POST_LIKE_FAILURE'

export const POST_UNLIKE_REQUEST = 'POST_UNLIKE_REQUEST'
export const POST_UNLIKE_SUCCESS = 'POST_UNLIKE_SUCCESS'
export const POST_UNLIKE_FAILURE = 'POST_UNLIKE_FAILURE'

export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST'
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS'
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE'

export const FETCH_GROUP_REQUEST = 'FETCH_GROUP_REQUEST'
export const FETCH_GROUP_SUCCESS = 'FETCH_GROUP_SUCCESS'
export const FETCH_GROUP_FAILURE = 'FETCH_GROUP_FAILURE'

export const LOGIN = 'LOGIN'

export const UPDATE_USER = 'UPDATE_USER'
export const ADD_GROUP = 'ADD_GROUP'
export const LEAVE_GROUP = 'LEAVE_GROUP'

export const GET_ALLEGIANCES = 'GET_ALLEGIANCES'
export const GET_ALLEGIANCES_REQUEST = 'GET_ALLEGIANCES_REQUEST'
export const GET_ALLEGIANCES_SUCCESS = 'GET_ALLEGIANCES_SUCCESS'
export const GET_ALLEGIANCES_FAILURE = 'GET_ALLEGIANCES_FAILURE'

export const ADD_ALLEGIANCES_REQUEST = 'GET_ALLEGIANCES_FAILURE'
export const ADD_ALLEGIANCES_SUCCESS = 'GET_ALLEGIANCES_FAILURE'
export const ADD_ALLEGIANCES_FAILURE = 'GET_ALLEGIANCES_FAILURE'

export const LEAVE_ALLEGIANCE = 'LEAVE_ALLEGIANCE'
// export const LEAVE_ALLEGIANCE = 'LEAVE_ALLEGIANCE'
// export const LEAVE_ALLEGIANCE = 'LEAVE_ALLEGIANCE'
// export const LEAVE_ALLEGIANCE = 'LEAVE_ALLEGIANCE'
export const ENTER_PROFILE = 'ENTER PROFILE'
