export const FETCH_INVITES_REQUEST = 'FETCH_INVITES_REQUEST'
export const FETCH_INVITES_SUCCESS = 'FETCH_INVITES_SUCCESS'
export const FETCH_INVITES_FAILURE = 'FETCH_INVITES_FAILURE'

export const DELETE_INVITES_REQUEST = 'DELETE_INVITES_REQUEST'
export const DELETE_INVITES_SUCCESS = 'DELETE_INVITES_SUCCESS'
export const DELETE_INVITES_FAILURE = 'DELETE_INVITES_FAILURE'

export const ACCEPT_INVITES_SUCCESS = 'ACCEPT_INVITES_SUCCESS'

export const DELETE_NOTIFICATIONS_REQUEST = 'DELETE_NOTIFICATIONS_REQUEST'
export const DELETE_NOTIFICATIONS_SUCCESS = 'DELETE_NOTIFICATIONS_SUCCESS'
export const DELETE_NOTIFICATIONS_FAILURE = 'DELETE_NOTIFICATIONS_FAILURE'

export const UPDATE_SOCKET = 'UPDATE_SOCKET'

export const FETCH_NOTIFICATIONS_REQUEST = 'FETCH_NOTIFICATIONS_REQUEST'
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS'
export const FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE'

export const CREATE_NOTIFICATION_SUCCESS = 'CREATE_NOTIFICATION_SUCCESS'
export const CREATE_INVITE_SUCCESS = 'CREATE_INVITE_SUCCESS'

export const RECEIVE_LIKE_SUCCESS = 'RECEIVE_LIKE_SUCCESS'
export const RECEIVE_DISLIKE_SUCCESS = 'RECEIVE_DISLIKE_SUCCESS'

export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE'

export const RECEIVE_POST_SUCCESS = 'RECEIVE_POST_SUCCESS'

export const POST_LIKE_REQUEST = 'POST_LIKE_REQUEST'
export const POST_LIKE_SUCCESS = 'POST_LIKE_SUCCESS'
export const POST_LIKE_FAILURE = 'POST_LIKE_FAILURE'

export const POST_UNLIKE_REQUEST = 'POST_UNLIKE_REQUEST'
export const POST_UNLIKE_SUCCESS = 'POST_UNLIKE_SUCCESS'
export const POST_UNLIKE_FAILURE = 'POST_UNLIKE_FAILURE'

export const FETCH_GROUP_REQUEST = 'FETCH_GROUP_REQUEST'
export const FETCH_GROUP_SUCCESS = 'FETCH_GROUP_SUCCESS'
export const FETCH_GROUP_FAILURE = 'FETCH_GROUP_FAILURE'

export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST'
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS'
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const ADD_GROUP_REQUEST = 'ADD_GROUP_REQUEST'
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS'
export const ADD_GROUP_FAILURE = 'ADD_GROUP_FAILURE'

export const LEAVE_GROUP_REQUEST = 'LEAVE_GROUP_REQUEST'
export const LEAVE_GROUP_SUCCESS = 'LEAVE_GROUP_SUCCESS'
export const LEAVE_GROUP_FAILURE = 'LEAVE_GROUP_FAILURE'

export const GET_ALLEGIANCES_REQUEST = 'GET_ALLEGIANCES_REQUEST'
export const GET_ALLEGIANCES_SUCCESS = 'GET_ALLEGIANCES_SUCCESS'
export const GET_ALLEGIANCES_FAILURE = 'GET_ALLEGIANCES_FAILURE'

export const ADD_ALLEGIANCES_REQUEST = 'ADD_ALLEGIANCES_FAILURE'
export const ADD_ALLEGIANCES_SUCCESS = 'ADD_ALLEGIANCES_SUCCESS'
export const ADD_ALLEGIANCES_FAILURE = 'ADD_ALLEGIANCES_FAILURE'
export const LEAVE_ALLEGIANCE_REQUEST = 'LEAVE_ALLEGIANCE_REQUEST'

export const LEAVE_ALLEGIANCE_SUCCESS = 'LEAVE_ALLEGIANCE_SUCCESS'
export const LEAVE_ALLEGIANCE_FAILURE = 'LEAVE_ALLEGIANCE_FAILURE'

export const LEAVE_ALLEGIANCE = 'LEAVE_ALLEGIANCE'

export const ENTER_PROFILE = 'ENTER PROFILE'

export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST'
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS'
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE'

export const REPLY_LIKE_REQUEST = 'REPLY_LIKE_REQUEST'
export const REPLY_LIKE_SUCCESS = 'REPLY_LIKE_SUCCESS'
export const REPLY_LIKE_FAILURE = 'REPLY_LIKE_FAILURE'

export const CREATE_REPLY_REQUEST = 'CREATE_REPLY_REQUEST'
export const CREATE_REPLY_SUCCESS = 'CREAT_REPLY_SUCCESS'
export const CREATE_REPLY_FAILURE = 'CREATE_REPLY_FAILURE'

export const REPLY_DISLIKE_REQUEST = 'REPLY_DISLIKE_REQUEST'
export const REPLY_DISLIKE_SUCCESS = 'REPLY_DISLIKE_SUCCESS'
export const REPLY_DISLIKE_FAILURE = 'REPLY_DISLIKE_FAILURE'

export const CLEAR_POSTS = 'CLEAR_POSTS'

export const SET_UNREAD_NOTIFICATION_NUM = 'SET_UNREAD_NOTIFICATION_NUM'

export const INCREMENT_UNREAD_NOTIFICATION_NUM =
  'INCREMENT_UNREAD_NOTIFICATION_NUM'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE'

export const DELETE_REPLY_REQUEST = 'DELETE_REPLY_REQUEST'
export const DELETE_REPLY_SUCCESS = 'DELETE_REPLY_SUCCESS'
export const DELETE_REPLY_FAILURE = 'DELETE_REPLY_FAILURE'

export const FETCH_PRIVATE_REQUEST = 'FETCH_PRIVATE_REQUEST'
export const FETCH_PRIVATE_SUCCESS = 'FETCH_PRIVATE_SUCCESS'
export const FETCH_PRIVATE_FAILURE = 'FETCH_PRIVATE_FAILURE'

export const JOIN_PRIVATE_REQUEST = 'JOIN_PRIVATE_REQUEST'
export const JOIN_PRIVATE_SUCCESS = 'JOIN_PRIVATE_SUCCESS'
export const JOIN_PRIVATE_FAILURE = 'JOIN_PRIVATE_FAILURE'

export const CANCEL_JOIN_PRIVATE_REQUEST = 'CANCEL_JOIN_PRIVATE_REQUEST'
export const CANCEL_JOIN_PRIVATE_SUCCESS = 'CANCEL_JOIN_PRIVATE_SUCCESS'
export const CANCEL_JOIN_PRIVATE_FAILURE = 'CANCEL_JOIN_PRIVATE_FAILURE'

export const EDIT_GROUP_REQUEST = 'EDIT_GROUP_REQUEST'
export const EDIT_GROUP_SUCCESS = 'EDIT_GROUP_SUCCESS'
export const EDIT_GROUP_FAILURE = 'EDIT_GROUP_FAILURE'

export const FETCH_MY_GROUPS_SUCCESS = 'FETCH_MY_GROUPS_SUCCESS'

export const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST'
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS'
export const DELETE_GROUP_FAILURE = 'DELETE_GROUP_FAILURE'

export const FETCH_MEMBER_TYPE_REQUEST = 'FETCH_MEMBER_TYPE_REQUEST'
export const FETCH_MEMBER_TYPE_SUCCESS = 'FETCH_MEMBER_TYPE_SUCCESS'
export const FETCH_MEMBER_TYPE_FAILURE = 'FETCH_MEMBER_TYPE_FAILURE'

export const EDIT_MEMBER_TYPE_REQUEST = 'EDIT_MEMBER_TYPE_REQUEST'
export const EDIT_MEMBER_TYPE_SUCCESS = 'EDIT_MEMBER_TYPE_SUCCESS'
export const EDIT_MEMBER_TYPE_FAILURE = 'EDIT_MEMBER_TYPE_FAILURE'

export const REMOVE_MEMBER_REQUEST = 'REMOVE_MEMBER_REQUEST'
export const REMOVE_MEMBER_SUCCESS = 'REMOVE_MEMBER_SUCCESS'
export const REMOVE_MEMBER_FAILURE = 'REMOVE_MEMBER_FAILURE'

export const ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS'

export const REMOVE_REQUEST_REQUEST = 'REMOVE_REQUEST_REQUEST'
export const REMOVE_REQUEST_SUCCESS = 'REMOVE_REQUEST_SUCCESS'
export const REMOVE_REQUEST_FAILURE = 'REMOVE_REQUEST_FAILURE'

export const CLEAN_UP_PENDING_GROUP_REQUESTS = 'CLEAN_UP_PENDING_GROUP_REQUESTS'

export const RECEIVE_REPLY_LIKE = 'RECEIVE_REPLY_LIKE'
export const RECEIVE_REPLY_DISLIKE = 'RECEIVE_REPLY_DISLIKE'

export const RECEIVE_GROUP_REPLY_SUCCESS = 'RECEIVE_GROUP_REPLY_SUCCESS'

export const RECEIVE_POST_REPLY_SUCCESS = 'RECEIVE_POST_REPLY_SUCCESS'
