export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE'

export const FETCH_PROFILE_POSTS_REQUEST = 'FETCH_PROFILE_POSTS_REQUEST'
export const FETCH_PROFILE_POSTS_SUCCESS = 'FETCH_PROFILE_POSTS_SUCCESS'
export const FETCH_PROFILE_POSTS_FAILURE = 'FETCH_PROFILE_POSTS_FAILURE'
